--Contraintes d'integrite
--b-clés étrangères

ALTER TABLE DETAILS_COMMANDES_EU_S
ADD CONSTRAINT FK_DETAILSCOMMANDES_PRODUITS
FOREIGN KEY (REF_PRODUIT) REFERENCES PRODUITS (REF_PRODUIT) ;

ALTER TABLE DETAILS_COMMANDES_EU_S
ADD CONSTRAINT FK_DETAILSCOMMANDES_COMMANDES
FOREIGN KEY (NO_COMMANDE) REFERENCES COMMANDES_EU_S (NO_COMMANDE) ;

ALTER TABLE STOCK_EU_S
ADD CONSTRAINT FK_STOCK_PRODUITS
FOREIGN KEY (REF_PRODUIT) REFERENCES PRODUITS (REF_PRODUIT) ;

ALTER TABLE COMMANDES_EU_S
ADD CONSTRAINT FK_COMMANDES_CLIENTS
FOREIGN KEY (CODE_CLIENT) REFERENCES CLIENTS_EU_S (CODE_CLIENT) ;

ALTER TABLE PRODUITS
ADD CONSTRAINT FK_PRODUITS_CATEGORIES
FOREIGN KEY (CODE_CATEGORIE) REFERENCES CATEGORIES (CODE_CATEGORIE) ;

