--mise en place des logs
CREATE MATERIALIZED VIEW LOG ON PRODUITS;

--mise en place des droits d’acces
GRANT SELECT ON MLOG$_PRODUITS TO CJAVERLIAT;
GRANT SELECT ON MLOG$_PRODUITS TO TBERTHIER;
