
--Netoyage du fragment EU du sud
-- En cas d’erreur 
DROP TABLE Commandes_eu_s CASCADE CONSTRAINTS;
DROP TABLE Details_Commandes_eu_s CASCADE CONSTRAINTS;
DROP TABLE Stock_eu_s CASCADE CONSTRAINTS;
DROP TABLE Clients_eu_s CASCADE CONSTRAINTS;
DROP TABLE Categories CASCADE CONSTRAINTS;
DROP TABLE Produits CASCADE CONSTRAINTS;

-- Avant de commencer la replication
DROP VIEW CLIENTS;
DROP VIEW COMMANDES;
DROP VIEW DETAILS_COMMANDES;
DROP VIEW EMPLOYES;
DROP VIEW FOURNISSEURS;
DROP VIEW STOCK;




