--Verifications, si la ligne est vide, c'est à dire qu'il n'y a
--aucune différence, les vues sont correctes
SELECT * FROM CLIENTS MINUS (SELECT * FROM Ryori.clients@DBLCentrale);
SELECT * FROM Ryori.clients@DBLCentrale MINUS (SELECT * FROM CLIENTS);

SELECT * FROM COMMANDES MINUS (SELECT * FROM Ryori.COMMANDES@DBLCentrale);
SELECT * FROM Ryori.COMMANDES@DBLCentrale MINUS (SELECT * FROM COMMANDES);

SELECT * FROM DETAILS_COMMANDES MINUS (SELECT * FROM Ryori.DETAILS_COMMANDES@DBLCentrale);
SELECT * FROM Ryori.DETAILS_COMMANDES@DBLCentrale MINUS (SELECT * FROM DETAILS_COMMANDES);

SELECT * FROM EMPLOYES MINUS (SELECT * FROM Ryori.EMPLOYES@DBLCentrale);
SELECT * FROM Ryori.clients@EMPLOYES MINUS (SELECT * FROM EMPLOYES);

SELECT * FROM STOCK MINUS (SELECT * FROM Ryori.STOCK@DBLCentrale);
SELECT * FROM Ryori.STOCK@DBLCentrale MINUS (SELECT * FROM STOCK);

SELECT * FROM PRODUITS MINUS (SELECT * FROM Ryori.PRODUITS@DBLCentrale);
SELECT * FROM Ryori.PRODUITS@DBLCentrale MINUS (SELECT * FROM PRODUITS);

SELECT * FROM CATEGORIES MINUS (SELECT * FROM Ryori.CATEGORIES@DBLCentrale);
SELECT * FROM Ryori.CATEGORIES@DBLCentrale MINUS (SELECT * FROM CATEGORIES);

SELECT * FROM FOURNISSEURS MINUS (SELECT * FROM Ryori.FOURNISSEURS@DBLCentrale);
SELECT * FROM Ryori.FOURNISSEURS@DBLCentrale MINUS (SELECT * FROM FOURNISSEURS);

--On obtient effectivement que des ensembles vides, donc on a bien
--la base centralisee equivalente a la base distribuee


