CREATE MATERIALIZED VIEW MVR_Employes
REFRESH COMPLETE
NEXT sysdate + (1/24/60)
AS
SELECT *
FROM TBERTHIER.EMPLOYES_AM@DBAmerique;

CREATE MATERIALIZED VIEW MVR_Produits
REFRESH FAST
NEXT sysdate + (1/24/60)
AS
SELECT * FROM AOULDHAMOU.PRODUITS@DBEuropeSud;

CREATE MATERIALIZED VIEW MVR_Categories
REFRESH FAST
NEXT sysdate + (1/24/60)
AS
SELECT * FROM AOULDHAMOU.CATEGORIES@DBEuropeSud;

CREATE MATERIALIZED VIEW LOG ON FOURNISSEURS;
GRANT SELECT ON MLOG$_FOURNISSEURS TO aouldhamou, tberthier;
-- La derniere ligne permet aux utilisateurs de faire un refresh start
-- sur la table des fournisseurs