--PK Clients

ALTER TABLE CLIENTS_EU_N
ADD CONSTRAINT PK_Clients_EU_N PRIMARY KEY (CODE_CLIENT);

ALTER TABLE CLIENTS_AUTRES
ADD CONSTRAINT PK_Clients_Autres PRIMARY KEY (CODE_CLIENT);

--PK Commandes

ALTER TABLE COMMANDES_EU_N
ADD CONSTRAINT PK_Commandes_EU_N PRIMARY KEY (NO_COMMANDE);

ALTER TABLE COMMANDES_AUTRES
ADD CONSTRAINT PK_Commandes_Autres PRIMARY KEY (NO_COMMANDE);

--PK Details commandes

ALTER TABLE DETAILS_COMMANDES_EU_N
ADD CONSTRAINT PK_Details_Commandes_EU_N PRIMARY KEY (NO_COMMANDE, REF_PRODUIT);

ALTER TABLE DETAILS_COMMANDES_AUTRES
ADD CONSTRAINT PK_Details_Commandes_Autres PRIMARY KEY (NO_COMMANDE, REF_PRODUIT);

--PK Fournisseurs

ALTER TABLE FOURNISSEURS
ADD CONSTRAINT PK_Fournisseurs PRIMARY KEY (NO_FOURNISSEUR);

--PK Stocks

ALTER TABLE STOCK_EU_N
ADD CONSTRAINT PK_Stock_EU_N PRIMARY KEY (REF_PRODUIT, PAYS);

ALTER TABLE STOCK_ALLEMAGNE
ADD CONSTRAINT PK_Stock_Allemagne PRIMARY KEY (REF_PRODUIT, PAYS);

ALTER TABLE STOCK_AUTRES
ADD CONSTRAINT PK_Stock_Autres PRIMARY KEY (REF_PRODUIT, PAYS);
