-- Suppression des tables

DROP TABLE CLIENTS_EU_N CASCADE CONSTRAINTS;
DROP TABLE CLIENTS_AUTRES CASCADE CONSTRAINTS;
DROP TABLE COMMANDE_EU_N CASCADE CONSTRAINTS;
DROP TABLE CLIENTS_AUTRES CASCADE CONSTRAINTS;
DROP TABLE DETAILS_COMMANDES_EU_N CASCADE CONSTRAINTS;
DROP TABLE DETAILS_COMMANDES_AUTRES CASCADE CONSTRAINTS;
DROP TABLE FOURNISSEURS CASCADE CONSTRAINTS;
DROP TABLE STOCK_EU_N CASCADE CONSTRAINTS;
DROP TABLE STOCK_ALLEMAGNE CASCADE CONSTRAINTS;
DROP TABLE STOCK_AUTRES CASCADE CONSTRAINTS;

-- Suppression des vues

DROP VIEW CLIENTS;
DROP VIEW COMMANDES;
DROP VIEW DETAILS_COMMANDES;
DROP VIEW STOCK;
DROP VIEW EMPLOYES;
DROP VIEW PRODUITS;
DROP VIEW CATEGORIES;
