CREATE MATERIALIZED VIEW MVR_Employes
REFRESH FAST
NEXT sysdate + (1/24/60)
AS
SELECT *
FROM TBERTHIER.EMPLOYES_AM@DBAmerique;

CREATE MATERIALIZED VIEW MVR_Produits
REFRESH FAST
NEXT sysdate + (1/24/60)
AS
SELECT * FROM AOULDHAMOU.PRODUITS@DBEuropeSud;

CREATE MATERIALIZED VIEW MVR_Categories
REFRESH COMPLETE
NEXT sysdate + (1/24/60)
AS
SELECT * FROM AOULDHAMOU.CATEGORIES@DBEuropeSud;
